#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-axiom-types
Version  : 0.1.1
Release  : 1
URL      : https://rubygems.org/downloads/axiom-types-0.1.1.gem
Source0  : https://rubygems.org/downloads/axiom-types-0.1.1.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-rdoc

%description
# axiom-types
Define types with optional constraints for use within axiom and other libraries.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n axiom-types-0.1.1
gem spec %{SOURCE0} -l --ruby > rubygem-axiom-types.gemspec

%build
gem build rubygem-axiom-types.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
axiom-types-0.1.1.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/axiom-types-0.1.1.gem
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Array/base%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Array/cdesc-Array.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Boolean/cdesc-Boolean.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Boolean/infer_from_primitive_class-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Class/cdesc-Class.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Collection/base%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Collection/cdesc-Collection.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Collection/finalize-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Collection/infer-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Collection/infer_from-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Collection/infer_from_primitive_instance-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Collection/match_primitive%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Collection/matches_member_type-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Collection/new_from-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Date/cdesc-Date.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/DateTime/cdesc-DateTime.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Decimal/cdesc-Decimal.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Encodable/ascii_compatible%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Encodable/cdesc-Encodable.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Encodable/extended-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Encodable/finalize-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Encodable/use_ascii_compatible_encoding-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Encodable/use_encoding-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Float/cdesc-Float.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Hash/base%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Hash/cdesc-Hash.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Hash/finalize-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Hash/infer-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Hash/infer_from-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Hash/infer_from_primitive_instance-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Hash/match_primitive%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Hash/matches_key_and_value_types-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Hash/new_from-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Infinity/%3c%3d%3e-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Infinity/cdesc-Infinity.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Infinity/coerce-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Infinity/inverse-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Infinity/succ-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Integer/cdesc-Integer.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/LengthComparable/cdesc-LengthComparable.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/LengthComparable/extended-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/LengthComparable/finalize-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/LengthComparable/range-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/LengthComparable/use_length_within_range-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/NegativeInfinity/%3c%3d%3e-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/NegativeInfinity/cdesc-NegativeInfinity.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Numeric/cdesc-Numeric.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Object/cdesc-Object.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Object/finalize-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Object/infer-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Object/infer_from_primitive_class-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Object/inherits_from_primitive-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Object/inspect-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Object/match_primitive%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Options/ReservedMethodError/cdesc-ReservedMethodError.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Options/accept_options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Options/accepted_options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Options/assert_method_available-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Options/cdesc-Options.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Options/define_option_method-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Options/inherited-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Options/options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Options/setup_option-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Set/base%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Set/cdesc-Set.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/String/cdesc-String.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Symbol/cdesc-Symbol.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/ThreadSafe/cdesc-ThreadSafe.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Time/cdesc-Time.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Type/add_constraint-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Type/anonymous%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Type/base%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Type/base-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Type/cdesc-Type.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Type/constraint-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Type/finalize-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Type/include%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Type/includes-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Type/infer-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/Type/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/ValueComparable/cdesc-ValueComparable.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/ValueComparable/extended-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/ValueComparable/finalize-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/ValueComparable/range-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/ValueComparable/use_value_within_range-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/cdesc-Types.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/finalize-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/Types/infer-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/Axiom/cdesc-Axiom.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/page-CONTRIBUTING_md.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/page-LICENSE.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/page-README_md.ri
/usr/lib64/ruby/gems/2.2.0/doc/axiom-types-0.1.1/ri/page-TODO.ri
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/.gitignore
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/.rspec
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/.rubocop.yml
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/.ruby-gemset
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/.travis.yml
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/.yardopts
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/CONTRIBUTING.md
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/Gemfile
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/Gemfile.devtools
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/Guardfile
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/README.md
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/TODO
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/axiom-types.gemspec
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/config/devtools.yml
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/config/flay.yml
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/config/flog.yml
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/config/mutant.yml
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/config/reek.yml
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/config/roodi.yml
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/config/rubocop.yml
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/config/yardstick.yml
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/lib/axiom-types.rb
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/lib/axiom/types.rb
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/lib/axiom/types/array.rb
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/lib/axiom/types/boolean.rb
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/lib/axiom/types/class.rb
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/lib/axiom/types/collection.rb
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/lib/axiom/types/date.rb
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/lib/axiom/types/date_time.rb
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/lib/axiom/types/decimal.rb
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/lib/axiom/types/encodable.rb
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/lib/axiom/types/float.rb
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/lib/axiom/types/hash.rb
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/lib/axiom/types/integer.rb
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/lib/axiom/types/length_comparable.rb
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/lib/axiom/types/numeric.rb
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/lib/axiom/types/object.rb
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/lib/axiom/types/set.rb
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/lib/axiom/types/string.rb
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/lib/axiom/types/support/infinity.rb
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/lib/axiom/types/support/options.rb
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/lib/axiom/types/symbol.rb
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/lib/axiom/types/time.rb
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/lib/axiom/types/type.rb
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/lib/axiom/types/value_comparable.rb
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/lib/axiom/types/version.rb
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/spec/unit/axiom/types/array/class_methods/infer_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/spec/unit/axiom/types/boolean/class_methods/infer_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/spec/unit/axiom/types/class_methods/finalize_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/spec/unit/axiom/types/class_methods/infer_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/spec/unit/axiom/types/collection/class_methods/finalize_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/spec/unit/axiom/types/collection/class_methods/infer_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/spec/unit/axiom/types/encodable/class_methods/extended_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/spec/unit/axiom/types/encodable/finalize_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/spec/unit/axiom/types/hash/class_methods/finalize_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/spec/unit/axiom/types/hash/class_methods/infer_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/spec/unit/axiom/types/infinity/coerce_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/spec/unit/axiom/types/infinity/spaceship_operator_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/spec/unit/axiom/types/infinity/succ_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/spec/unit/axiom/types/length_comparable/class_methods/extended_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/spec/unit/axiom/types/length_comparable/finalize_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/spec/unit/axiom/types/length_comparable/range_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/spec/unit/axiom/types/negative_infinity/spaceship_operator_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/spec/unit/axiom/types/object/class_methods/coercion_method_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/spec/unit/axiom/types/object/class_methods/finalize_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/spec/unit/axiom/types/object/class_methods/infer_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/spec/unit/axiom/types/object/class_methods/inspect_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/spec/unit/axiom/types/object/class_methods/primitive_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/spec/unit/axiom/types/options/accept_options_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/spec/unit/axiom/types/options/inherited_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/spec/unit/axiom/types/set/class_methods/infer_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/spec/unit/axiom/types/type/class_methods/anonymous_predicate_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/spec/unit/axiom/types/type/class_methods/base_predicate_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/spec/unit/axiom/types/type/class_methods/base_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/spec/unit/axiom/types/type/class_methods/constraint_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/spec/unit/axiom/types/type/class_methods/finalize_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/spec/unit/axiom/types/type/class_methods/include_predicate_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/spec/unit/axiom/types/type/class_methods/includes_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/spec/unit/axiom/types/type/class_methods/infer_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/spec/unit/axiom/types/type/class_methods/new_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/spec/unit/axiom/types/value_comparable/class_methods/extended_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/spec/unit/axiom/types/value_comparable/finalize_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/axiom-types-0.1.1/spec/unit/axiom/types/value_comparable/range_spec.rb
/usr/lib64/ruby/gems/2.2.0/specifications/axiom-types-0.1.1.gemspec
